### ISSUE TITLE
Via should not inject to the platform class loader

### ISSUE THREAD

**Issue by aromaa** [ViaVersion/ViaSponge#9]
Via is currently injecting to the platform class loader [here](https://github.com/ViaVersion/ViaSponge/blob/f0d3b5e8ecb115f0566328ef503b35622c5d61fc/src/main/java/com/viaversion/sponge/ViaSpongePlugin.java#L90). First of all, this breaks on modern ModLauncher version which uses the JPMS platform which we are now using on 1.21.1.

This is also not something that is supported. Is there something that is blocking going trough the normal plugin bootstrapping? Can the Sponge team provide assistance here?

**Comment by FlorianMichael** [comment]
Thank you for reaching out!

ViaSponge needs to load the ViaVersion (and optionally ViaBackwards, ViaRewind) jar files into the plugin class loader in order to initialize them as ViaSponge serves as the platform implementation code for Sponge. We previously had the sponge platform code inbuilt in every project which needed no workaround, but is now required since the VV/VB/VR jar files don't contain the sponge plugin anymore.

Does the Sponge API provides API for plugins to load external jar files into their class loaders?

**Comment by aromaa** [comment]
> We previously had the sponge platform code inbuilt in every project which needed no workaround

Were there any particular paint points with this design? Even simple plugin declaration using the gradle plugin or by manually providing sponge_plugins.json for each jar would let them participate in the plugin loader. You do however need to provide a entrypoint, but we can relax this restriction if needed.

I would see two options working:
- Have the loader specific logic in SpongeVia and provide each jar with the plugin metadata.
- Have the main logic in ViaVersion and provide each extension jar with the plugin metadata.

Are there some specific issues encountered with these options?

> Does the Sponge API provides API for plugins to load external jar files into their class loaders?

If it comes to that, this would be extension to the plugin loader. You would declare this in the plugin metadata and we figure it out for you.

**Comment by aromaa** [comment]
You can also define the entrypoints inside the ViaSponge plugin and make the other projects point directly to it. As long as you define ViaSponge as the dependency, it should work fine.

If we decide to relax the entrypoint requirement, it would only apply to the latest version. Something to take in to the consideration if you wish to keep the backwards compatibility for older releases.
